### ISSUE TITLE
Language syntax doesn't admit spaces before parens

### ISSUE THREAD

**Issue by ulidtko** [Mercury-Language/mercury#29]
This is OK:

    :- pred main(io::di, io::uo) is det.

This refuses to compile:

    :- pred main (io::di, io::uo) is det.
                ^

because of the space marked above. Error message:

    hello.m:006: Syntax error at token ` (': operator or `.' expected.

**Comment by zsomogyi** [comment]
The Mercury language DOES admit spaces before parentheses; it just gives
the resulting text different meaning. Name followed by parentheses with no space in between
means call: name followed by parentheses with space in between means some other language
construct, such as an operator applied to a parenthesized term This may not be what you expected,
but it is what the language prescribes.

This behavior is inherited from the syntax of Prolog. While Prolog compatibility
is no longer important for Mercury, changing such basic aspects of the language design
would lead to huge disruptions for very little real benefit. We therefore won't be doing it.

**Comment by ulidtko** [comment]
How is either a call or an operator application possible in a `:- pred` declaration?

Coming from Haskell, I also don't understand the difference between a call and an operator application.

**Comment by ulidtko** [comment]
> The Mercury language DOES admit spaces before parentheses

Why is it giving me the Syntax Error above then?

**Comment by zsomogyi** [comment]
Semantically, a call such as "or(A, B)" and an operator application such as
"A `or` (B)" can be identical, but syntactically, they are different.

The reason why you get the error is because the spurious space changes
the syntactic meaning of the declaration. The compiler expects to see a well formed
operator application, and finds a malformed one instead.

For well formed operator applications in predicate declarations, see e.g.
the int.m module of the Mercury standard library. (This is operator application
in the syntactic sense.)
