### ISSUE TITLE
Lambda scoping error

### ISSUE THREAD

**Issue by ulidtko** [Mercury-Language/mercury#31]
```
mdb> query
?- [list].
:- import_module list.
?- filter( (pred(W::in) is semidet :- W \= 5), 1..10, Ans).
<stdin>:012: In clause for `run(di, uo)':
<stdin>:012:   mode error: argument 1 had the wrong instantiatedness.
<stdin>:012:   Final instantiatedness of `V_11' was `unique(mdb_query.res(free,
<stdin>:012:   ground))',
<stdin>:012:   expected final instantiatedness was `ground'.
<stdin>:026: In clause for predicate `mdb_query.query'/2:
<stdin>:026:   warning: variable `W' occurs only once in this scope.
<stdin>:026: Inferred :- pred query(T1, list.list(int)).
<stdin>:026: Inferred :- mode query(out(free), out) is det.
mdb_query.m:005: In predicate `run'/2:
mdb_query.m:005:   warning: unresolved polymorphism.
mdb_query.m:005:   The variables with unbound types were:
mdb_query.m:005:     W: T
mdb_query.m:005:     W: T
mdb_query.m:005:     V_20: mdb_query.res(T, list.list(int))
mdb_query.m:005:     V_11: mdb_query.res(T, list.list(int))
mdb_query.m:005:     V_10: pred(mdb_query.res(T, list.list(int)), io.state,
mdb_query.m:005:     io.state)
mdb_query.m:005:     V_9: (pred mdb_query.res(T, list.list(int)))
mdb_query.m:005:   The unbound type variables will be implicitly bound to the
mdb_query.m:005:   builtin type `void'.
For more information, recompile with `-E'.
Compilation error(s) occurred.
```

Two flashing things here:

 * `warning: variable 'W' occurs only once in this scope.` — this clearly isn't true, `W` is written twice: once in the lambda arg decl, once in the lambda body.

 * **two** `W: T` variables in the typechecker log.

Looks like a compiler bug to me.

**Comment by ulidtko** [comment]
Even this triggers:

    ?- P = (pred(W::in) is semidet :- true).

**Comment by mgudemann** [comment]
Hi @ulidtko ,

be careful, the mdb query is not a REPL.

This is neither a compiler bug nor a scoping error, but a problem with how the query is translated by the debugger. Your examples work without problems when used in a compiled module.

For mdb, this works:
```
?- P = (pred(_::in) is semidet :- true).
<stdin>:001: Inferred :- pred query(mdb_query.inputs, (pred V_1)).
mdb_query.m:008: In predicate `run'/3:
mdb_query.m:008:   warning: unresolved polymorphism.
mdb_query.m:008:   The variable with an unbound type was:
mdb_query.m:008:     P: (pred V_1)
mdb_query.m:008:   The unbound type variable will be implicitly bound to the
mdb_query.m:008:   builtin type `void'.
P = 'lambda_<stdin>_1'(void), true ;
fail.
No (more) solutions.
```
This works for mdb for your first example:
```
?- filter( (pred(W::in) is semidet :- W \= 5), 1..10, Ans), W = [1].
<stdin>:001: In clause for predicate `mdb_query.query'/3:
<stdin>:001:   warning: variable `W' has overlapping scopes.
<stdin>:001: Inferred :- pred query(mdb_query.inputs, list.list(int),
<stdin>:001:   list.list(int)).
W = [1], Ans = [1, 2, 3, 4, 6, 7, 8, 9, 10], true ;
fail.
No (more) solutions.
```

The FAQ states: "For ‘query’ and ‘cc_query’, the debugger will print out all the variables in the goal using ‘io.write’. The goal must bind all of its variables to ground terms, otherwise you will get a mode error."

W is a variable in your query, the translation therefore wants to print the value of the variable W, as it seems not to consider that it occurs in a lambda abstraction. This is the reason why simply specifying W with any ground value (any type) works.

**Comment by ulidtko** [comment]
Hi Matthias!

Could you please link the FAQ mentioned? I don't find anything 'query' and 'cc_query'-related here:

http://mercurylang.org/information/doc-release/mercury_faq/index.html

**Comment by mgudemann** [comment]
hi @ulidtko 

ok, isorry t is in the **user's guide**, not the FAQ: http://mercurylang.org/information/doc-release/mercury_user_guide/Interactive-query-commands.html#Interactive-query-commands

again, I really suggest you ask these questions on the users mailing list https://www.mercurylang.org/lists/listinfo/users

**Comment by zsomogyi** [comment]
As Mathias said, the query command is NOT intended to be a REPL.

Due to the semantic checks required, a REPL is much more work in Mercury
than in e.g. Lisp, and due to the same semantic checks, it buys you much less.
As a consequence, in 22 years of Mercury development, we never felt enough
of a need for a REPL to invest the time and effort required to implement one.

Since it is easy enough to write the code you want to test in the source file itself,
and just call the predicate containing that code via "query", we haven't written
any code to analyze the query to see e.g. whether it contains any lambdas.
Any such analysis code would stand at the top of a *very* long slippery slope.
Once you move away from the stance "query does not analyze the code
it is handing off to the Mercury compiler" , the scope of the analyses it can
perform, and that some users may expect it to perform, is limited only by
the capability of the Mercury compiler itself. We have felt no need to give ourselves
the obligation to maintain a code base parallel to the compiler for the analysis
of Mercury code. On the contrary, we actively want to avoid such double maintenance
burdens.

It may be possible to do what you want without starting down that slope
by improving the coordination between the debugger's query command
and the compiler, e.g. by having query pass an option the compiler asking it
to do something out of the ordinary. However, to the best of my knowledge,
noone on the Mercury team considers this to be at all a priority, so if you want
this functionality, you will have to implement it yourself.

**Comment by ulidtko** [comment]
@zsomogyi I acknowledge the technical difficulty of implementing a REPL for Mercury. However, please note that 22 years of Mercury development inevitably blurs the picture of how a **new user** approaches the language. You *know* the language; new users don't.

And for new users, a REPL is an **incredibly** useful tool for language exploration and quick testing of ideas. Especially when the documentation is scarce and stagnating.

Why does SWI Prolog has a REPL (and Mercury doesn't)? Take any major language: Python, Haskell, heck even C++ [has got a REPL][cint], despite it's quite complicated compilation model.

Compiling scratch files is so a poor substitute for a proper REPL, that I can't even tell whether `mdb query` is worse. And I need to write *7 lines of code* for the **absolute minimum** Hello World? And I need to explicitly import blink-of-an-eye-basic stuff like bools, ints and strings? Heck no, that's not going to work for *quick testing of ideas*.

To repeat: with all the different backends of MMC (C#, Java, Erlang, LLVM) I see that a proper REPL isn't so easy. How about a dedicated `bytecode` grade designed specifically for on-the-fly runtime interpretation of Mercury code? Or something like that. Somehow, all the other compilers manage to leverage their usual semantic checks without duplication (when compiling a string of user code to bytecode, I mean). What's wrong with that?

[cint]: https://root.cern.ch/cint

**Comment by zsomogyi** [comment]
I agree that a REPL can be useful; you don't have to convince me of that. That is not the point.

If you want one for Mercury, you have three choices.

A: write it yourself. B: pay someone to write it for you. C: wait for someone else to write it.

I estimate that it would take me about 8 to 12 months to implement a REPL. Would you be willing to give me
120K USD for that? If not, you can find someone else, or choose between A and C.

And for your information: the REPLs for Prolog and Python don't replace the semantic checks
of their compiler versions because they have no meaningful semantic checks to duplicate
(and most Prolog dialects don't have compilers anyway). The REPLs for Haskell and C/C++,
on the other hand, both started out as separate entities from the compilers for their languages
(e.g. hugs vs ghc) and duplicated large amounts of functionality.
