### ISSUE TITLE
configure test for "mercury_cv_gcc_labels" is testing unsupported behavior

### ISSUE THREAD

**Issue by he32** [Mercury-Language/mercury#44]
I noticed while trying to build this for NetBSD/macppc (powerpc), that this particular
configure test was looping endlessly.  Suspecting this to be a compiler bug, as when
compiled with -O1 it "works" but with "-O2" or higher it loops.  However, it has been
pointed out to me what the GCC documentation says about this mechanism:

```
   "You may not use this mechanism to jump to code in a different function.
   If you do that, totally unpredictable things happen.  The best way to
   avoid this is to store the label address only in automatic variables and
   never pass it as an argument."
```

So the configure test itself is testing unsupported / undefined behavior.
I've not looked at whether the code itself tries to use this same behavior,
but have my suspicions...

**Comment by wangp** [comment]
It does test for unsupported behaviour because some of the *low-level* C grades depend on non-local gotos, including the most commonly used one called `asm_fast.gc`. If non-local gotos do not work on a particular platform then other low-level C grades must be used (with a performance penalty), commonly`reg.gc` (uses gcc global registers extension) or `none.gc` (no gcc extensions).

There are also high-level C grades (`hlc.gc`, `hlc.par.gc`) which perform well and should work basically anywhere. The high-level C grades do not support debugging or deep profiling, though.

In the configure script you should find a big block of platforms for which non-local gotos or asm labels are not used.

**Comment by wangp** [comment]
I have disabled the gcc labels check on powerpc.
